### PR TITLE
Cleaning and updating

### PR DESCRIPTION
**Pull request by julianu**
- cleaned the Nextflow folder of results
- added label definitions to perform processes in parallel 
- results are stored in separate folders and using copies instead of links (which are complicated to copy :smirk:)
- uploaded some results

### CODE REVIEW

**Comment by veitveit** [comment]
@julianu I found the problem. The Dockerfile uses the wrong paths for the conda environment, which you changed to nf-core-compomics-workflow. 
Can you change all these paths in the Dockerfile? Then it should work.

**Comment by julianu** [comment]
Yes, I did not test the Docker, sorry.
Will do later.

**Comment by julianu** [comment]
The building seems to work now, only the pushing to Docker hub not.
I guess this is either because I changed the docker-image.yml for the PR (changed the working-directory), or there are no credentials given for a PR build?

Either way, a push from a PR is probably not intended? Should this be removed from the docker-image.yml?

**Comment by veitveit** [comment]
Hmmm, I wasn't aware of this one:
"With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository."

So the credentials are not passed and therefore fails. 

You are right that the docker image should not be pushed before accepting the pull request. Nice catch! Is there are a way to do this?

The same actually applies for the releases.

**Comment by julianu** [comment]
I tried to fix this in the docker-image.yml and it works now, at least for this PR state.

@di-hardt, can you briefly check whether it will do, what we expect it to do? I think, there might still be an issue, that the containers are build (and pushed?) twice for both tested Nextflow versions?

**Comment by di-hardt** [comment]
Looks good to me.

**Comment by di-hardt** [comment]
Looks good to me.
But I think you are right about the redundant building and pushing of the image.
The problem is `strategy.matrix` which runs the job for each given element.
Is this even necessary? We assign `strategy.matrix.nxf_ver` to the environment variable `NXF_VER` which is not used in the action itself nor in the Dockerfile or somewhere else. And Nextflow is installed by `wget -qO- get.nextflow.io | bash` which always installs the newest version.
Maybe I miss something?

**Pull request merged**
